### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by SevenBits** [unetbootin/unetbootin.github.com#3]
Geza, you should probably force HTTPS on this site to protect your users from MiTM attacks. I’ve done the same for Mac Linux USB Loader.

You can enable this option under the repository settings, in the ‘GitHub Pages’ section.

**Comment by qwertychouskie** [comment]
@gkovacs Is there any reason this hasn't been done yet?  Manually going to https://unetbootin.github.io works just fine, so forcing HTTPS shouldn't break anything.

**Comment by abitrolly** [comment]
@gkovacs go to https://github.com/unetbootin/unetbootin.github.com/settings and check **Force HTTPS**. That's it.

**Comment by gkovacs** [comment]
done

**Comment by abitrolly** [comment]
You may want to update URL at https://github.com/unetbootin/unetbootin.github.com to avoid redirect.
