### ISSUE TITLE
Web structure

### ISSUE THREAD

**Issue by coppolaemilio** [unetbootin/unetbootin.github.com#4]
Is there any reason why this website source code is so unorganized? do you want a hand with it? I could spend a few hours this weekend making it look nicer. 
Cheers!

**Comment by gkovacs** [comment]
sure if you want to make some visual improvements to the site you're welcome to make a pull request! the actual code is in https://github.com/unetbootin/unetbootin.github.com/blob/master/index.html I think I wrote the bulk in 2007 and it was one of the first websites I wrote (also had to worry about supporting browsers like IE5...) hence why it doesn't look so beautiful.

or if you mean the various directories, they're there to provide redirects to downloads for isos/executables

**Comment by qwertychouskie** [comment]
I'm working on an updated version now:
[UNetbootin-site-new.zip](https://github.com/unetbootin/unetbootin.github.com/files/957095/UNetbootin-site-new.zip)
Hopefully will get a PR made soon.

**Comment by gkovacs** [comment]
Excellent, I like the direction you're taking it, looking forward to the PR!

**Comment by qwertychouskie** [comment]
PR made, see https://github.com/unetbootin/unetbootin.github.com/pull/5.

**Comment by gkovacs** [comment]
Thanks, merged!
